### ISSUE TITLE
Solar systems selected page on docs is not the same color

### ISSUE THREAD

**Issue by blockninja124** [Cosmic-Mod/Cosmic-Mod.github.io#2]
When in the docs, selecting a new page will turn the current page blue. However when selecting solar systems, it doesnt go blue it stays a gray.

Image showing this:
![BUG](https://github.com/user-attachments/assets/31c48259-ad10-4402-8c27-dda00a3d6647)

**Comment by jcm236** [comment]
Huh

**Comment by jcm236** [comment]
I'll try to find a fix

**Comment by jcm236** [comment]
Fixed in 87dbe48
