### ISSUE TITLE
The drop-downs have plain text

### ISSUE THREAD

**Issue by jcm236** [Cosmic-Mod/Cosmic-Mod.github.io#3]
The drop-downs here: https://cosmic-mod.github.io/addonsupport/planets/ do not have their contents rendered. One solution may be to port all the drop-downs to [bulma modal cards](https://bulma.io/documentation/components/modal/#modal-card)

**Comment by blockninja124** [comment]
More specifically, their markdown isn't being converted

**Comment by blockninja124** [comment]
I think this is a bug with bulma clean theme, so I've reported it [here](https://github.com/chrisrhymes/bulma-clean-theme/issues/167). If it ends up being working as intended or won't fix, we might still need an alternative

**Comment by jcm236** [comment]
Nah it's not - jekyll doesn't convert stuff inside html tags, I know how to fix this

**Comment by jcm236** [comment]
Added spoiler include in 817a535. Check planets page for example.
