### ISSUE TITLE
Warning tag sticks out of the page on mobile

### ISSUE THREAD

**Issue by jcm236** [Cosmic-Mod/Cosmic-Mod.github.io#4]
The red warning sticks out of the page on mobile https://cosmic-mod.github.io/ . 
Possible fixes:
- Shorten the text and use an icon instead
- Port it to bulma notifications

**Comment by jcm236** [comment]
Text shortened in 87dbe48

**Comment by blockninja124** [comment]
I'm going to close this issue for now. Feel free to reopen it if you think it needs more fixing or is still happening
